// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentalCarsApi.Data;

#nullable disable

namespace RentalCarsApi.Migrations
{
    [DbContext(typeof(RentalCarsDbContext))]
    partial class RentalCarsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RentalCarsApi.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRented")
                        .HasColumnType("bit");

                    b.Property<int>("Milage")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            IsRented = false,
                            Milage = 156000,
                            Name = "Opel Astra"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            IsRented = false,
                            Milage = 230526,
                            Name = "Volvo V70"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            IsRented = false,
                            Milage = 122000,
                            Name = "Opel V90"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            IsRented = false,
                            Milage = 172340,
                            Name = "Opel XC90"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            IsRented = false,
                            Milage = 154794,
                            Name = "Opel XC60"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            IsRented = false,
                            Milage = 254786,
                            Name = "Opel XC40"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            IsRented = false,
                            Milage = 204413,
                            Name = "Chrysler Pacifica"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            IsRented = false,
                            Milage = 11445,
                            Name = "Ferrari Enzo"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            IsRented = false,
                            Milage = 10224,
                            Name = "Lamborghini Aventador"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            IsRented = false,
                            Milage = 12000,
                            Name = "Opel Meriva"
                        });
                });

            modelBuilder.Entity("RentalCarsApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Compact"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Premium"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Minivan"
                        });
                });

            modelBuilder.Entity("RentalCarsApi.Models.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("BaseDayRental")
                        .HasColumnType("float");

                    b.Property<double>("KilometerPrice")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Prices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseDayRental = 10.0,
                            KilometerPrice = 1.0,
                            Name = "Standard"
                        });
                });

            modelBuilder.Entity("RentalCarsApi.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReservationNumber")
                        .HasColumnType("int");

                    b.Property<string>("TimeDateRental")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeDateReturn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("ReservationNumber")
                        .IsUnique();

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            CustomerBirth = "1984-07-04-1111",
                            ReservationNumber = 1000,
                            TimeDateRental = "220401",
                            TimeDateReturn = "220401"
                        },
                        new
                        {
                            Id = 2,
                            CarId = 4,
                            CustomerBirth = "1974-08-04-1112",
                            ReservationNumber = 2000,
                            TimeDateRental = "220402",
                            TimeDateReturn = "220402"
                        },
                        new
                        {
                            Id = 3,
                            CarId = 6,
                            CustomerBirth = "1964-09-04-1113",
                            ReservationNumber = 3000,
                            TimeDateRental = "220403",
                            TimeDateReturn = "220403"
                        });
                });

            modelBuilder.Entity("RentalCarsApi.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BookingNumber")
                        .HasColumnType("int");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalRentalDays")
                        .HasColumnType("int");

                    b.Property<double>("RentalPrice")
                        .HasColumnType("float");

                    b.Property<string>("TimeDateRental")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeDateReturn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingNumber")
                        .IsUnique();

                    b.HasIndex("CarId");

                    b.ToTable("Rentals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingNumber = 1000,
                            CarId = 1,
                            CustomerBirth = "1984-07-04-1111",
                            RentalDays = 1,
                            RentalPrice = 1000.0,
                            TimeDateRental = "220401",
                            TimeDateReturn = "220401"
                        },
                        new
                        {
                            Id = 2,
                            BookingNumber = 2000,
                            CarId = 4,
                            CustomerBirth = "1974-07-04-1112",
                            RentalDays = 1,
                            RentalPrice = 2000.0,
                            TimeDateRental = "220402",
                            TimeDateReturn = "220402"
                        },
                        new
                        {
                            Id = 3,
                            BookingNumber = 3000,
                            CarId = 6,
                            CustomerBirth = "1964-07-04-1113",
                            RentalDays = 1,
                            RentalPrice = 3000.0,
                            TimeDateRental = "220403",
                            TimeDateReturn = "220403"
                        });
                });

            modelBuilder.Entity("RentalCarsApi.Models.Car", b =>
                {
                    b.HasOne("RentalCarsApi.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RentalCarsApi.Models.Reservation", b =>
                {
                    b.HasOne("RentalCarsApi.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("RentalCarsApi.Rental", b =>
                {
                    b.HasOne("RentalCarsApi.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });
#pragma warning restore 612, 618
        }
    }
}
